# yt-dlp config — simpan di C:\Users\<nama_user>\AppData\Roaming\yt-dlp\config.txt
# Atau di folder yang sama dengan server.py sebagai yt-dlp.conf

--cookies cookies.txt
--remote-components ejs:github